### PR TITLE
(chore) update changelog details

### PR DESCRIPTION
**Pull request by HillaryManning**
### Changelog
None

### Docs
None

### Description

Adding details about 'ignore-for-changelog' tag and how to handle feature flags.

### CODE REVIEW

**Review by defunctzombie — COMMENTED** [review]
> : this will add the 'ignore-for-changelog' tag

As someone making a PR - I would say I don't really care about this nuance.

---
My opinion is there are too many words here and that folks will not read all this. I would cut down on the words and make this easier to follow.

**Comment by HillaryManning** [comment]
> > : this will add the 'ignore-for-changelog' tag
> 
> As someone making a PR - I would say I don't really care about this nuance.
> 
> My opinion is there are too many words here and that folks will not read all this. I would cut down on the words and make this easier to follow.

As someone making a PR I care about that nuance because maybe I made a PR with no updates (wrote 'none' and got the tag), but then received PR feedback that led to more changes/something that should be included in the changelog (<-- this has happened to me multiple times). If I understand correctly: the tag would not be automatically removed even if I update the description (or would it?) and I should remove the tag manually.

Happy to simplify the text 👍

**Comment by defunctzombie** [comment]
> If I understand correctly: the tag would not be automatically removed even if I update the description (or would it?) and I should remove the tag manually.

@bahram should fix this if the tag is not removed automatically. No engineer should be managing this tag - all you need to do is ensure the PR description is good and accurate.

**Review by banisadr — CHANGES_REQUESTED** [review]
> If I understand correctly: the tag would not be automatically removed even if I update the description (or would it?) and I should remove the tag manually.

The check runs with each update to a PR in the app repo and adds or removes the tag accordingly. You shouldn't need to pay attention to the tag. If it's not, that would be helpful to know & I can fix it.

Nuance is this only applies to the app repo. This PR sets the default for the Foxglove org. Probably needs to move to the `/foxglove/app/.github` file.

> all you need to do is ensure the PR description is good and accurate.

Agreed this is how it should work—my goal is to reduce overhead, not add

**Comment by HillaryManning** [comment]
Sounds like we don't think this level of detail is necessary, closing after the overview today in all-hands.

**Pull request closed without merging**
