### PR TITLE
Use headings in pull request template

### PR DESCRIPTION
**Pull request by james-rms**

### CODE REVIEW

**Comment by amacneil** [comment]
I personally find h2 pretty aggressive. Also not sure we want to mention linear in our PR template given that OSS folks see it?

@defunctzombie can make a call on this, I am not in github enough

fyi I edited this PR description to use the template, as an example

**Comment by defunctzombie** [comment]
I agree - the h2 are rather aggressive. h3 maybe? That still provides h4, and h5 for use by the author? I am 👍 On changing these to headers away from "bold". Here was the original discussion: https://github.com/foxglove/console/pull/2047

FWIW when you actually merge the PR the styling does not display anymore in the github UI. Don't think that changes my feelings here, only wanted to surface this: https://github.com/foxglove/studio/commit/1d518e948acb748bac6790039277695d2825c53c

And yes please remove Linear from the template. I don't include linear issues in the description when I use the branch name from linear since that part is handled automatically by linear so unless I am referencing a GitHub issue as well I don't add any additional references. I think the commented out reminder is sufficient.

**Comment by jtbandes** [comment]
Should we remove https://github.com/foxglove/studio/blob/main/.github/pull_request_template.md?plain=1 so that this also gets used for studio? Or is it intentional that they're different? cc @esthersweon

**Comment by esthersweon** [comment]
@jtbandes – Not intentional. We can use this one template for Studio.

Would want to add the following comments then in this template:
- Add a `docs` label if this change requires documentation updates
- Use relevant metric tracking to assess the performance of new and experimental features

**Pull request merged**
